/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// InlineResponse20046 struct for InlineResponse20046
type InlineResponse20046 struct {
	Data *[]ListCampaignStoreBudgets `json:"data,omitempty"`
}

// NewInlineResponse20046 instantiates a new InlineResponse20046 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20046() *InlineResponse20046 {
	this := InlineResponse20046{}
	return &this
}

// NewInlineResponse20046WithDefaults instantiates a new InlineResponse20046 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20046WithDefaults() *InlineResponse20046 {
	this := InlineResponse20046{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InlineResponse20046) GetData() []ListCampaignStoreBudgets {
	if o == nil || o.Data == nil {
		var ret []ListCampaignStoreBudgets
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20046) GetDataOk() (*[]ListCampaignStoreBudgets, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InlineResponse20046) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []ListCampaignStoreBudgets and assigns it to the Data field.
func (o *InlineResponse20046) SetData(v []ListCampaignStoreBudgets) {
	o.Data = &v
}

func (o InlineResponse20046) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20046 struct {
	value *InlineResponse20046
	isSet bool
}

func (v NullableInlineResponse20046) Get() *InlineResponse20046 {
	return v.value
}

func (v *NullableInlineResponse20046) Set(val *InlineResponse20046) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20046) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20046) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20046(val *InlineResponse20046) *NullableInlineResponse20046 {
	return &NullableInlineResponse20046{value: val, isSet: true}
}

func (v NullableInlineResponse20046) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20046) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
