/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// UpdateCampaignCollection struct for UpdateCampaignCollection
type UpdateCampaignCollection struct {
	// A short description of the purpose of this collection.
	Description *string `json:"description,omitempty"`
}

// NewUpdateCampaignCollection instantiates a new UpdateCampaignCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildUpdateCampaignCollection() *UpdateCampaignCollection {
	this := UpdateCampaignCollection{}
	return &this
}

// NewUpdateCampaignCollectionWithDefaults instantiates a new UpdateCampaignCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCampaignCollectionWithDefaults() *UpdateCampaignCollection {
	this := UpdateCampaignCollection{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateCampaignCollection) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCampaignCollection) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateCampaignCollection) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateCampaignCollection) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateCampaignCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateCampaignCollection struct {
	value *UpdateCampaignCollection
	isSet bool
}

func (v NullableUpdateCampaignCollection) Get() *UpdateCampaignCollection {
	return v.value
}

func (v *NullableUpdateCampaignCollection) Set(val *UpdateCampaignCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCampaignCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCampaignCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableUpdateCampaignCollection(val *UpdateCampaignCollection) *NullableUpdateCampaignCollection {
	return &NullableUpdateCampaignCollection{value: val, isSet: true}
}

func (v NullableUpdateCampaignCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCampaignCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
