/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// OktaEvent Single event definition in the event data emitted by Okta.
type OktaEvent struct {
	// Event type defining an action.
	EventType string            `json:"eventType"`
	Target    []OktaEventTarget `json:"target"`
}

// NewOktaEvent instantiates a new OktaEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildOktaEvent(eventType string, target []OktaEventTarget) *OktaEvent {
	this := OktaEvent{}
	this.EventType = eventType
	this.Target = target
	return &this
}

// NewOktaEventWithDefaults instantiates a new OktaEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOktaEventWithDefaults() *OktaEvent {
	this := OktaEvent{}
	return &this
}

// GetEventType returns the EventType field value
func (o *OktaEvent) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *OktaEvent) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *OktaEvent) SetEventType(v string) {
	o.EventType = v
}

// GetTarget returns the Target field value
func (o *OktaEvent) GetTarget() []OktaEventTarget {
	if o == nil {
		var ret []OktaEventTarget
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *OktaEvent) GetTargetOk() (*[]OktaEventTarget, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *OktaEvent) SetTarget(v []OktaEventTarget) {
	o.Target = v
}

func (o OktaEvent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["eventType"] = o.EventType
	}
	if true {
		toSerialize["target"] = o.Target
	}
	return json.Marshal(toSerialize)
}

type NullableOktaEvent struct {
	value *OktaEvent
	isSet bool
}

func (v NullableOktaEvent) Get() *OktaEvent {
	return v.value
}

func (v *NullableOktaEvent) Set(val *OktaEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableOktaEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableOktaEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableOktaEvent(val *OktaEvent) *NullableOktaEvent {
	return &NullableOktaEvent{value: val, isSet: true}
}

func (v NullableOktaEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOktaEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
