/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// AccountDashboardStatisticDiscount struct for AccountDashboardStatisticDiscount
type AccountDashboardStatisticDiscount struct {
	// Total discount value redeemed by users.
	Total float32 `json:"total"`
	// Average discount percentage.
	Average float32 `json:"average"`
	// Values aggregated for the specified date.
	Datetime time.Time `json:"datetime"`
}

// NewAccountDashboardStatisticDiscount instantiates a new AccountDashboardStatisticDiscount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountDashboardStatisticDiscount(total float32, average float32, datetime time.Time) *AccountDashboardStatisticDiscount {
	this := AccountDashboardStatisticDiscount{}
	this.Total = total
	this.Average = average
	this.Datetime = datetime
	return &this
}

// NewAccountDashboardStatisticDiscountWithDefaults instantiates a new AccountDashboardStatisticDiscount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountDashboardStatisticDiscountWithDefaults() *AccountDashboardStatisticDiscount {
	this := AccountDashboardStatisticDiscount{}
	return &this
}

// GetTotal returns the Total field value
func (o *AccountDashboardStatisticDiscount) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AccountDashboardStatisticDiscount) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AccountDashboardStatisticDiscount) SetTotal(v float32) {
	o.Total = v
}

// GetAverage returns the Average field value
func (o *AccountDashboardStatisticDiscount) GetAverage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Average
}

// GetAverageOk returns a tuple with the Average field value
// and a boolean to check if the value has been set.
func (o *AccountDashboardStatisticDiscount) GetAverageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Average, true
}

// SetAverage sets field value
func (o *AccountDashboardStatisticDiscount) SetAverage(v float32) {
	o.Average = v
}

// GetDatetime returns the Datetime field value
func (o *AccountDashboardStatisticDiscount) GetDatetime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Datetime
}

// GetDatetimeOk returns a tuple with the Datetime field value
// and a boolean to check if the value has been set.
func (o *AccountDashboardStatisticDiscount) GetDatetimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Datetime, true
}

// SetDatetime sets field value
func (o *AccountDashboardStatisticDiscount) SetDatetime(v time.Time) {
	o.Datetime = v
}

func (o AccountDashboardStatisticDiscount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["total"] = o.Total
	}
	if true {
		toSerialize["average"] = o.Average
	}
	if true {
		toSerialize["datetime"] = o.Datetime
	}
	return json.Marshal(toSerialize)
}

type NullableAccountDashboardStatisticDiscount struct {
	value *AccountDashboardStatisticDiscount
	isSet bool
}

func (v NullableAccountDashboardStatisticDiscount) Get() *AccountDashboardStatisticDiscount {
	return v.value
}

func (v *NullableAccountDashboardStatisticDiscount) Set(val *AccountDashboardStatisticDiscount) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountDashboardStatisticDiscount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountDashboardStatisticDiscount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountDashboardStatisticDiscount(val *AccountDashboardStatisticDiscount) *NullableAccountDashboardStatisticDiscount {
	return &NullableAccountDashboardStatisticDiscount{value: val, isSet: true}
}

func (v NullableAccountDashboardStatisticDiscount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountDashboardStatisticDiscount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
