/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// ScimGroupMember Member of the SCIM group. In Talon.One, the member is a [user](https://docs.talon.one/docs/product/account/account-settings/managing-users) assigned to a specific role.
type ScimGroupMember struct {
	// Unique identifier of the member.
	Value *string `json:"value,omitempty"`
	// Identifier of the user. This is usually an email address.
	Display *string `json:"display,omitempty"`
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ScimGroupMember) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ScimGroupMember) GetValueOk() (string, bool) {
	if o == nil || o.Value == nil {
		var ret string
		return ret, false
	}
	return *o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ScimGroupMember) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ScimGroupMember) SetValue(v string) {
	o.Value = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *ScimGroupMember) GetDisplay() string {
	if o == nil || o.Display == nil {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ScimGroupMember) GetDisplayOk() (string, bool) {
	if o == nil || o.Display == nil {
		var ret string
		return ret, false
	}
	return *o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *ScimGroupMember) HasDisplay() bool {
	if o != nil && o.Display != nil {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *ScimGroupMember) SetDisplay(v string) {
	o.Display = &v
}

type NullableScimGroupMember struct {
	Value        ScimGroupMember
	ExplicitNull bool
}

func (v NullableScimGroupMember) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableScimGroupMember) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
