/*
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// InlineResponse20013 struct for InlineResponse20013
type InlineResponse20013 struct {
	HasMore bool                  `json:"hasMore"`
	Data    []ApplicationCustomer `json:"data"`
}

// GetHasMore returns the HasMore field value
func (o *InlineResponse20013) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// SetHasMore sets field value
func (o *InlineResponse20013) SetHasMore(v bool) {
	o.HasMore = v
}

// GetData returns the Data field value
func (o *InlineResponse20013) GetData() []ApplicationCustomer {
	if o == nil {
		var ret []ApplicationCustomer
		return ret
	}

	return o.Data
}

// SetData sets field value
func (o *InlineResponse20013) SetData(v []ApplicationCustomer) {
	o.Data = v
}

type NullableInlineResponse20013 struct {
	Value        InlineResponse20013
	ExplicitNull bool
}

func (v NullableInlineResponse20013) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableInlineResponse20013) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
