/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// ErrorSource The source of the current error, exactly one of `pointer`, `parameter` or `line` will be defined. 
type ErrorSource struct {
	// Pointer to the path in the payload that caused this error.
	Pointer *string `json:"pointer,omitempty"`
	// Query parameter that caused this error.
	Parameter *string `json:"parameter,omitempty"`
	// Line number in uploaded multipart file that caused this error. 'N/A' if unknown.
	Line *string `json:"line,omitempty"`
	// Pointer to the resource that caused this error.
	Resource *string `json:"resource,omitempty"`
}

// GetPointer returns the Pointer field value if set, zero value otherwise.
func (o *ErrorSource) GetPointer() string {
	if o == nil || o.Pointer == nil {
		var ret string
		return ret
	}
	return *o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ErrorSource) GetPointerOk() (string, bool) {
	if o == nil || o.Pointer == nil {
		var ret string
		return ret, false
	}
	return *o.Pointer, true
}

// HasPointer returns a boolean if a field has been set.
func (o *ErrorSource) HasPointer() bool {
	if o != nil && o.Pointer != nil {
		return true
	}

	return false
}

// SetPointer gets a reference to the given string and assigns it to the Pointer field.
func (o *ErrorSource) SetPointer(v string) {
	o.Pointer = &v
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *ErrorSource) GetParameter() string {
	if o == nil || o.Parameter == nil {
		var ret string
		return ret
	}
	return *o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ErrorSource) GetParameterOk() (string, bool) {
	if o == nil || o.Parameter == nil {
		var ret string
		return ret, false
	}
	return *o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *ErrorSource) HasParameter() bool {
	if o != nil && o.Parameter != nil {
		return true
	}

	return false
}

// SetParameter gets a reference to the given string and assigns it to the Parameter field.
func (o *ErrorSource) SetParameter(v string) {
	o.Parameter = &v
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *ErrorSource) GetLine() string {
	if o == nil || o.Line == nil {
		var ret string
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ErrorSource) GetLineOk() (string, bool) {
	if o == nil || o.Line == nil {
		var ret string
		return ret, false
	}
	return *o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *ErrorSource) HasLine() bool {
	if o != nil && o.Line != nil {
		return true
	}

	return false
}

// SetLine gets a reference to the given string and assigns it to the Line field.
func (o *ErrorSource) SetLine(v string) {
	o.Line = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *ErrorSource) GetResource() string {
	if o == nil || o.Resource == nil {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ErrorSource) GetResourceOk() (string, bool) {
	if o == nil || o.Resource == nil {
		var ret string
		return ret, false
	}
	return *o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *ErrorSource) HasResource() bool {
	if o != nil && o.Resource != nil {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *ErrorSource) SetResource(v string) {
	o.Resource = &v
}

type NullableErrorSource struct {
	Value ErrorSource
	ExplicitNull bool
}

func (v NullableErrorSource) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableErrorSource) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
