/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// RuleMetadata struct for RuleMetadata
type RuleMetadata struct {
	// A short description of the rule.
	Title string `json:"title"`
	// A customer-facing name for the rule.
	DisplayName *string `json:"displayName,omitempty"`
	// A customer-facing description that explains the details of the rule.   For example, this property can contain details about eligibility requirements, reward timelines, or terms and conditions.
	DisplayDescription *string `json:"displayDescription,omitempty"`
	// Any additional data associated with the rule, such as an image URL, vendor name, or a content management system (CMS) ID.
	RelatedData *string `json:"relatedData,omitempty"`
}

// NewRuleMetadata instantiates a new RuleMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildRuleMetadata(title string) *RuleMetadata {
	this := RuleMetadata{}
	this.Title = title
	return &this
}

// NewRuleMetadataWithDefaults instantiates a new RuleMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleMetadataWithDefaults() *RuleMetadata {
	this := RuleMetadata{}
	return &this
}

// GetTitle returns the Title field value
func (o *RuleMetadata) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *RuleMetadata) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *RuleMetadata) SetTitle(v string) {
	o.Title = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *RuleMetadata) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleMetadata) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *RuleMetadata) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *RuleMetadata) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayDescription returns the DisplayDescription field value if set, zero value otherwise.
func (o *RuleMetadata) GetDisplayDescription() string {
	if o == nil || o.DisplayDescription == nil {
		var ret string
		return ret
	}
	return *o.DisplayDescription
}

// GetDisplayDescriptionOk returns a tuple with the DisplayDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleMetadata) GetDisplayDescriptionOk() (*string, bool) {
	if o == nil || o.DisplayDescription == nil {
		return nil, false
	}
	return o.DisplayDescription, true
}

// HasDisplayDescription returns a boolean if a field has been set.
func (o *RuleMetadata) HasDisplayDescription() bool {
	if o != nil && o.DisplayDescription != nil {
		return true
	}

	return false
}

// SetDisplayDescription gets a reference to the given string and assigns it to the DisplayDescription field.
func (o *RuleMetadata) SetDisplayDescription(v string) {
	o.DisplayDescription = &v
}

// GetRelatedData returns the RelatedData field value if set, zero value otherwise.
func (o *RuleMetadata) GetRelatedData() string {
	if o == nil || o.RelatedData == nil {
		var ret string
		return ret
	}
	return *o.RelatedData
}

// GetRelatedDataOk returns a tuple with the RelatedData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleMetadata) GetRelatedDataOk() (*string, bool) {
	if o == nil || o.RelatedData == nil {
		return nil, false
	}
	return o.RelatedData, true
}

// HasRelatedData returns a boolean if a field has been set.
func (o *RuleMetadata) HasRelatedData() bool {
	if o != nil && o.RelatedData != nil {
		return true
	}

	return false
}

// SetRelatedData gets a reference to the given string and assigns it to the RelatedData field.
func (o *RuleMetadata) SetRelatedData(v string) {
	o.RelatedData = &v
}

func (o RuleMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["title"] = o.Title
	}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.DisplayDescription != nil {
		toSerialize["displayDescription"] = o.DisplayDescription
	}
	if o.RelatedData != nil {
		toSerialize["relatedData"] = o.RelatedData
	}
	return json.Marshal(toSerialize)
}

type NullableRuleMetadata struct {
	value *RuleMetadata
	isSet bool
}

func (v NullableRuleMetadata) Get() *RuleMetadata {
	return v.value
}

func (v *NullableRuleMetadata) Set(val *RuleMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableRuleMetadata(val *RuleMetadata) *NullableRuleMetadata {
	return &NullableRuleMetadata{value: val, isSet: true}
}

func (v NullableRuleMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
