/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// StrikethroughLabelingNotification The strikethrough labels notification for an application.
type StrikethroughLabelingNotification struct {
	// The version of the strikethrough pricing notification.
	Version *string `json:"version,omitempty"`
	// Timestamp at which the strikethrough pricing update becomes valid. Set for **scheduled** strikethrough pricing updates (version: v2) only.
	ValidFrom *time.Time `json:"validFrom,omitempty"`
	// The ID of the Application to which the catalog items labels belongs.
	ApplicationId int64 `json:"applicationId"`
	// The batch number of the notification. Notifications might be sent in different batches.
	CurrentBatch int64 `json:"currentBatch"`
	// The total number of batches for the notification.
	TotalBatches int64                      `json:"totalBatches"`
	Trigger      StrikethroughTrigger       `json:"trigger"`
	ChangedItems []StrikethroughChangedItem `json:"changedItems"`
	// The type of the notification
	NotificationType string `json:"NotificationType"`
}

// NewStrikethroughLabelingNotification instantiates a new StrikethroughLabelingNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrikethroughLabelingNotification(applicationId int64, currentBatch int64, totalBatches int64, trigger StrikethroughTrigger, changedItems []StrikethroughChangedItem, notificationType string) *StrikethroughLabelingNotification {
	this := StrikethroughLabelingNotification{}
	this.ApplicationId = applicationId
	this.CurrentBatch = currentBatch
	this.TotalBatches = totalBatches
	this.Trigger = trigger
	this.ChangedItems = changedItems
	this.NotificationType = notificationType
	return &this
}

// NewStrikethroughLabelingNotificationWithDefaults instantiates a new StrikethroughLabelingNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrikethroughLabelingNotificationWithDefaults() *StrikethroughLabelingNotification {
	this := StrikethroughLabelingNotification{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *StrikethroughLabelingNotification) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *StrikethroughLabelingNotification) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *StrikethroughLabelingNotification) SetVersion(v string) {
	o.Version = &v
}

// GetValidFrom returns the ValidFrom field value if set, zero value otherwise.
func (o *StrikethroughLabelingNotification) GetValidFrom() time.Time {
	if o == nil || o.ValidFrom == nil {
		var ret time.Time
		return ret
	}
	return *o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetValidFromOk() (*time.Time, bool) {
	if o == nil || o.ValidFrom == nil {
		return nil, false
	}
	return o.ValidFrom, true
}

// HasValidFrom returns a boolean if a field has been set.
func (o *StrikethroughLabelingNotification) HasValidFrom() bool {
	if o != nil && o.ValidFrom != nil {
		return true
	}

	return false
}

// SetValidFrom gets a reference to the given time.Time and assigns it to the ValidFrom field.
func (o *StrikethroughLabelingNotification) SetValidFrom(v time.Time) {
	o.ValidFrom = &v
}

// GetApplicationId returns the ApplicationId field value
func (o *StrikethroughLabelingNotification) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *StrikethroughLabelingNotification) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetCurrentBatch returns the CurrentBatch field value
func (o *StrikethroughLabelingNotification) GetCurrentBatch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CurrentBatch
}

// GetCurrentBatchOk returns a tuple with the CurrentBatch field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetCurrentBatchOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBatch, true
}

// SetCurrentBatch sets field value
func (o *StrikethroughLabelingNotification) SetCurrentBatch(v int64) {
	o.CurrentBatch = v
}

// GetTotalBatches returns the TotalBatches field value
func (o *StrikethroughLabelingNotification) GetTotalBatches() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalBatches
}

// GetTotalBatchesOk returns a tuple with the TotalBatches field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetTotalBatchesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalBatches, true
}

// SetTotalBatches sets field value
func (o *StrikethroughLabelingNotification) SetTotalBatches(v int64) {
	o.TotalBatches = v
}

// GetTrigger returns the Trigger field value
func (o *StrikethroughLabelingNotification) GetTrigger() StrikethroughTrigger {
	if o == nil {
		var ret StrikethroughTrigger
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetTriggerOk() (*StrikethroughTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *StrikethroughLabelingNotification) SetTrigger(v StrikethroughTrigger) {
	o.Trigger = v
}

// GetChangedItems returns the ChangedItems field value
func (o *StrikethroughLabelingNotification) GetChangedItems() []StrikethroughChangedItem {
	if o == nil {
		var ret []StrikethroughChangedItem
		return ret
	}

	return o.ChangedItems
}

// GetChangedItemsOk returns a tuple with the ChangedItems field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetChangedItemsOk() (*[]StrikethroughChangedItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangedItems, true
}

// SetChangedItems sets field value
func (o *StrikethroughLabelingNotification) SetChangedItems(v []StrikethroughChangedItem) {
	o.ChangedItems = v
}

// GetNotificationType returns the NotificationType field value
func (o *StrikethroughLabelingNotification) GetNotificationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationType
}

// GetNotificationTypeOk returns a tuple with the NotificationType field value
// and a boolean to check if the value has been set.
func (o *StrikethroughLabelingNotification) GetNotificationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationType, true
}

// SetNotificationType sets field value
func (o *StrikethroughLabelingNotification) SetNotificationType(v string) {
	o.NotificationType = v
}

func (o StrikethroughLabelingNotification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.ValidFrom != nil {
		toSerialize["validFrom"] = o.ValidFrom
	}
	if true {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if true {
		toSerialize["currentBatch"] = o.CurrentBatch
	}
	if true {
		toSerialize["totalBatches"] = o.TotalBatches
	}
	if true {
		toSerialize["trigger"] = o.Trigger
	}
	if true {
		toSerialize["changedItems"] = o.ChangedItems
	}
	if true {
		toSerialize["NotificationType"] = o.NotificationType
	}
	return json.Marshal(toSerialize)
}

type NullableStrikethroughLabelingNotification struct {
	value *StrikethroughLabelingNotification
	isSet bool
}

func (v NullableStrikethroughLabelingNotification) Get() *StrikethroughLabelingNotification {
	return v.value
}

func (v *NullableStrikethroughLabelingNotification) Set(val *StrikethroughLabelingNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableStrikethroughLabelingNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableStrikethroughLabelingNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrikethroughLabelingNotification(val *StrikethroughLabelingNotification) *NullableStrikethroughLabelingNotification {
	return &NullableStrikethroughLabelingNotification{value: val, isSet: true}
}

func (v NullableStrikethroughLabelingNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrikethroughLabelingNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
