/*
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// MultipleCustomerProfileIntegrationRequestItem struct for MultipleCustomerProfileIntegrationRequestItem
type MultipleCustomerProfileIntegrationRequestItem struct {
	// Arbitrary properties associated with this item
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	// The custom identifier for this profile, must be unique within the account.
	IntegrationId string `json:"integrationId"`
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *MultipleCustomerProfileIntegrationRequestItem) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MultipleCustomerProfileIntegrationRequestItem) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret, false
	}
	return *o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *MultipleCustomerProfileIntegrationRequestItem) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *MultipleCustomerProfileIntegrationRequestItem) SetAttributes(v map[string]interface{}) {
	o.Attributes = &v
}

// GetIntegrationId returns the IntegrationId field value
func (o *MultipleCustomerProfileIntegrationRequestItem) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// SetIntegrationId sets field value
func (o *MultipleCustomerProfileIntegrationRequestItem) SetIntegrationId(v string) {
	o.IntegrationId = v
}

type NullableMultipleCustomerProfileIntegrationRequestItem struct {
	Value        MultipleCustomerProfileIntegrationRequestItem
	ExplicitNull bool
}

func (v NullableMultipleCustomerProfileIntegrationRequestItem) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableMultipleCustomerProfileIntegrationRequestItem) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
