/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// MultipleAudiencesItem struct for MultipleAudiencesItem
type MultipleAudiencesItem struct {
	// The internal ID of this entity.
	Id int64 `json:"id"`
	// The time this entity was created.
	Created time.Time `json:"created"`
	// The human-friendly display name for this audience.
	Name string `json:"name"`
	// The ID of this audience in the third-party integration.
	IntegrationId string `json:"integrationId"`
	// Indicates whether the audience is new, updated or unmodified by the request.
	Status string `json:"status"`
}

// NewMultipleAudiencesItem instantiates a new MultipleAudiencesItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultipleAudiencesItem(id int64, created time.Time, name string, integrationId string, status string) *MultipleAudiencesItem {
	this := MultipleAudiencesItem{}
	this.Id = id
	this.Created = created
	this.Name = name
	this.IntegrationId = integrationId
	this.Status = status
	return &this
}

// NewMultipleAudiencesItemWithDefaults instantiates a new MultipleAudiencesItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultipleAudiencesItemWithDefaults() *MultipleAudiencesItem {
	this := MultipleAudiencesItem{}
	return &this
}

// GetId returns the Id field value
func (o *MultipleAudiencesItem) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MultipleAudiencesItem) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MultipleAudiencesItem) SetId(v int64) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *MultipleAudiencesItem) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *MultipleAudiencesItem) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *MultipleAudiencesItem) SetCreated(v time.Time) {
	o.Created = v
}

// GetName returns the Name field value
func (o *MultipleAudiencesItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MultipleAudiencesItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MultipleAudiencesItem) SetName(v string) {
	o.Name = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *MultipleAudiencesItem) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *MultipleAudiencesItem) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *MultipleAudiencesItem) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetStatus returns the Status field value
func (o *MultipleAudiencesItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MultipleAudiencesItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MultipleAudiencesItem) SetStatus(v string) {
	o.Status = v
}

func (o MultipleAudiencesItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["integrationId"] = o.IntegrationId
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableMultipleAudiencesItem struct {
	value *MultipleAudiencesItem
	isSet bool
}

func (v NullableMultipleAudiencesItem) Get() *MultipleAudiencesItem {
	return v.value
}

func (v *NullableMultipleAudiencesItem) Set(val *MultipleAudiencesItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMultipleAudiencesItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMultipleAudiencesItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultipleAudiencesItem(val *MultipleAudiencesItem) *NullableMultipleAudiencesItem {
	return &NullableMultipleAudiencesItem{value: val, isSet: true}
}

func (v NullableMultipleAudiencesItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultipleAudiencesItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
