/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// BaseNotificationEntity struct for BaseNotificationEntity
type BaseNotificationEntity struct {
	// Indicates which notification properties to apply.
	Policy map[string]interface{} `json:"policy"`
	// Indicates whether the notification is activated.
	Enabled *bool `json:"enabled,omitempty"`
}

// NewBaseNotificationEntity instantiates a new BaseNotificationEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildBaseNotificationEntity(policy map[string]interface{}) *BaseNotificationEntity {
	this := BaseNotificationEntity{}
	this.Policy = policy
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// NewBaseNotificationEntityWithDefaults instantiates a new BaseNotificationEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseNotificationEntityWithDefaults() *BaseNotificationEntity {
	this := BaseNotificationEntity{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetPolicy returns the Policy field value
func (o *BaseNotificationEntity) GetPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *BaseNotificationEntity) GetPolicyOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *BaseNotificationEntity) SetPolicy(v map[string]interface{}) {
	o.Policy = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *BaseNotificationEntity) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseNotificationEntity) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *BaseNotificationEntity) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *BaseNotificationEntity) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o BaseNotificationEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["policy"] = o.Policy
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableBaseNotificationEntity struct {
	value *BaseNotificationEntity
	isSet bool
}

func (v NullableBaseNotificationEntity) Get() *BaseNotificationEntity {
	return v.value
}

func (v *NullableBaseNotificationEntity) Set(val *BaseNotificationEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseNotificationEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseNotificationEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableBaseNotificationEntity(val *BaseNotificationEntity) *NullableBaseNotificationEntity {
	return &NullableBaseNotificationEntity{value: val, isSet: true}
}

func (v NullableBaseNotificationEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseNotificationEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
