/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// CustomerAchievement A customer's progress in an achievement, together with the achievement definition.
type CustomerAchievement struct {
	// The internal ID of the achievement.
	Id int64 `json:"id"`
	// The internal name of the achievement used in API requests.
	Name string `json:"name"`
	// The display name of the achievement in the Campaign Manager.
	Title string `json:"title"`
	// The description of the achievement in the Campaign Manager.
	Description string `json:"description"`
	// The required number of actions or the transactional milestone to complete the achievement.
	Target float32 `json:"target"`
	// The policy that determines if and how the achievement recurs. - `no_recurrence`: The achievement can be completed only once. - `on_expiration`: The achievement resets after it expires and becomes available again. - `on_completion`: When the customer progress status reaches `completed`, the achievement resets and becomes available again.
	RecurrencePolicy string `json:"recurrencePolicy"`
	// The policy that determines how the achievement starts, ends, or resets. - `user_action`: The achievement ends or resets relative to when the customer started the achievement. - `fixed_schedule`: The achievement starts, ends, or resets for all customers following a fixed schedule.
	ActivationPolicy string `json:"activationPolicy"`
	// The achievement's start date when `activationPolicy` is equal to `fixed_schedule`.  **Note:** It is an RFC3339 timestamp string.
	FixedStartDate *time.Time `json:"fixedStartDate,omitempty"`
	// The achievement's end date. If defined, customers cannot participate in the achievement after this date.  **Note:** It is an RFC3339 timestamp string.
	EndDate *time.Time `json:"endDate,omitempty"`
	// When `true`, customer progress can be rolled back in completed achievements.
	AllowRollbackAfterCompletion bool `json:"allowRollbackAfterCompletion"`
	// This property is **deprecated**. Use `referencedByCampaigns` instead. This field contains the first campaign ID from the related `referencedByCampaigns`, and is omitted when `referencedByCampaigns` is empty.
	CampaignId *int64 `json:"campaignId,omitempty"`
	// The IDs of the campaigns that reference this achievement, in ascending order.
	CampaignIds []int64 `json:"campaignIds"`
	// The campaigns that reference this achievement. They are sorted in ascending order by their `id`.
	ReferencedByCampaigns []CampaignReference  `json:"referencedByCampaigns"`
	CurrentProgress       *AchievementProgress `json:"currentProgress,omitempty"`
}

// NewCustomerAchievement instantiates a new CustomerAchievement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCustomerAchievement(id int64, name string, title string, description string, target float32, recurrencePolicy string, activationPolicy string, allowRollbackAfterCompletion bool, campaignIds []int64, referencedByCampaigns []CampaignReference) *CustomerAchievement {
	this := CustomerAchievement{}
	this.Id = id
	this.Name = name
	this.Title = title
	this.Description = description
	this.Target = target
	this.RecurrencePolicy = recurrencePolicy
	this.ActivationPolicy = activationPolicy
	this.AllowRollbackAfterCompletion = allowRollbackAfterCompletion
	this.CampaignIds = campaignIds
	this.ReferencedByCampaigns = referencedByCampaigns
	return &this
}

// NewCustomerAchievementWithDefaults instantiates a new CustomerAchievement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerAchievementWithDefaults() *CustomerAchievement {
	this := CustomerAchievement{}
	return &this
}

// GetId returns the Id field value
func (o *CustomerAchievement) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerAchievement) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CustomerAchievement) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerAchievement) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *CustomerAchievement) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CustomerAchievement) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value
func (o *CustomerAchievement) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CustomerAchievement) SetDescription(v string) {
	o.Description = v
}

// GetTarget returns the Target field value
func (o *CustomerAchievement) GetTarget() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetTargetOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *CustomerAchievement) SetTarget(v float32) {
	o.Target = v
}

// GetRecurrencePolicy returns the RecurrencePolicy field value
func (o *CustomerAchievement) GetRecurrencePolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecurrencePolicy
}

// GetRecurrencePolicyOk returns a tuple with the RecurrencePolicy field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetRecurrencePolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecurrencePolicy, true
}

// SetRecurrencePolicy sets field value
func (o *CustomerAchievement) SetRecurrencePolicy(v string) {
	o.RecurrencePolicy = v
}

// GetActivationPolicy returns the ActivationPolicy field value
func (o *CustomerAchievement) GetActivationPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActivationPolicy
}

// GetActivationPolicyOk returns a tuple with the ActivationPolicy field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetActivationPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivationPolicy, true
}

// SetActivationPolicy sets field value
func (o *CustomerAchievement) SetActivationPolicy(v string) {
	o.ActivationPolicy = v
}

// GetFixedStartDate returns the FixedStartDate field value if set, zero value otherwise.
func (o *CustomerAchievement) GetFixedStartDate() time.Time {
	if o == nil || o.FixedStartDate == nil {
		var ret time.Time
		return ret
	}
	return *o.FixedStartDate
}

// GetFixedStartDateOk returns a tuple with the FixedStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetFixedStartDateOk() (*time.Time, bool) {
	if o == nil || o.FixedStartDate == nil {
		return nil, false
	}
	return o.FixedStartDate, true
}

// HasFixedStartDate returns a boolean if a field has been set.
func (o *CustomerAchievement) HasFixedStartDate() bool {
	if o != nil && o.FixedStartDate != nil {
		return true
	}

	return false
}

// SetFixedStartDate gets a reference to the given time.Time and assigns it to the FixedStartDate field.
func (o *CustomerAchievement) SetFixedStartDate(v time.Time) {
	o.FixedStartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *CustomerAchievement) GetEndDate() time.Time {
	if o == nil || o.EndDate == nil {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetEndDateOk() (*time.Time, bool) {
	if o == nil || o.EndDate == nil {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *CustomerAchievement) HasEndDate() bool {
	if o != nil && o.EndDate != nil {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *CustomerAchievement) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetAllowRollbackAfterCompletion returns the AllowRollbackAfterCompletion field value
func (o *CustomerAchievement) GetAllowRollbackAfterCompletion() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowRollbackAfterCompletion
}

// GetAllowRollbackAfterCompletionOk returns a tuple with the AllowRollbackAfterCompletion field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetAllowRollbackAfterCompletionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowRollbackAfterCompletion, true
}

// SetAllowRollbackAfterCompletion sets field value
func (o *CustomerAchievement) SetAllowRollbackAfterCompletion(v bool) {
	o.AllowRollbackAfterCompletion = v
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *CustomerAchievement) GetCampaignId() int64 {
	if o == nil || o.CampaignId == nil {
		var ret int64
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetCampaignIdOk() (*int64, bool) {
	if o == nil || o.CampaignId == nil {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *CustomerAchievement) HasCampaignId() bool {
	if o != nil && o.CampaignId != nil {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given int64 and assigns it to the CampaignId field.
func (o *CustomerAchievement) SetCampaignId(v int64) {
	o.CampaignId = &v
}

// GetCampaignIds returns the CampaignIds field value
func (o *CustomerAchievement) GetCampaignIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.CampaignIds
}

// GetCampaignIdsOk returns a tuple with the CampaignIds field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetCampaignIdsOk() (*[]int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignIds, true
}

// SetCampaignIds sets field value
func (o *CustomerAchievement) SetCampaignIds(v []int64) {
	o.CampaignIds = v
}

// GetReferencedByCampaigns returns the ReferencedByCampaigns field value
func (o *CustomerAchievement) GetReferencedByCampaigns() []CampaignReference {
	if o == nil {
		var ret []CampaignReference
		return ret
	}

	return o.ReferencedByCampaigns
}

// GetReferencedByCampaignsOk returns a tuple with the ReferencedByCampaigns field value
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetReferencedByCampaignsOk() (*[]CampaignReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferencedByCampaigns, true
}

// SetReferencedByCampaigns sets field value
func (o *CustomerAchievement) SetReferencedByCampaigns(v []CampaignReference) {
	o.ReferencedByCampaigns = v
}

// GetCurrentProgress returns the CurrentProgress field value if set, zero value otherwise.
func (o *CustomerAchievement) GetCurrentProgress() AchievementProgress {
	if o == nil || o.CurrentProgress == nil {
		var ret AchievementProgress
		return ret
	}
	return *o.CurrentProgress
}

// GetCurrentProgressOk returns a tuple with the CurrentProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAchievement) GetCurrentProgressOk() (*AchievementProgress, bool) {
	if o == nil || o.CurrentProgress == nil {
		return nil, false
	}
	return o.CurrentProgress, true
}

// HasCurrentProgress returns a boolean if a field has been set.
func (o *CustomerAchievement) HasCurrentProgress() bool {
	if o != nil && o.CurrentProgress != nil {
		return true
	}

	return false
}

// SetCurrentProgress gets a reference to the given AchievementProgress and assigns it to the CurrentProgress field.
func (o *CustomerAchievement) SetCurrentProgress(v AchievementProgress) {
	o.CurrentProgress = &v
}

func (o CustomerAchievement) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["target"] = o.Target
	}
	if true {
		toSerialize["recurrencePolicy"] = o.RecurrencePolicy
	}
	if true {
		toSerialize["activationPolicy"] = o.ActivationPolicy
	}
	if o.FixedStartDate != nil {
		toSerialize["fixedStartDate"] = o.FixedStartDate
	}
	if o.EndDate != nil {
		toSerialize["endDate"] = o.EndDate
	}
	if true {
		toSerialize["allowRollbackAfterCompletion"] = o.AllowRollbackAfterCompletion
	}
	if o.CampaignId != nil {
		toSerialize["campaignId"] = o.CampaignId
	}
	if true {
		toSerialize["campaignIds"] = o.CampaignIds
	}
	if true {
		toSerialize["referencedByCampaigns"] = o.ReferencedByCampaigns
	}
	if o.CurrentProgress != nil {
		toSerialize["currentProgress"] = o.CurrentProgress
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerAchievement struct {
	value *CustomerAchievement
	isSet bool
}

func (v NullableCustomerAchievement) Get() *CustomerAchievement {
	return v.value
}

func (v *NullableCustomerAchievement) Set(val *CustomerAchievement) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAchievement) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAchievement) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCustomerAchievement(val *CustomerAchievement) *NullableCustomerAchievement {
	return &NullableCustomerAchievement{value: val, isSet: true}
}

func (v NullableCustomerAchievement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAchievement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
