/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// CampaignTemplate struct for CampaignTemplate
type CampaignTemplate struct {
	// The internal ID of this entity.
	Id int64 `json:"id"`
	// The time this entity was created.
	Created time.Time `json:"created"`
	// The ID of the account that owns this entity.
	AccountId int64 `json:"accountId"`
	// The ID of the user associated with this entity.
	UserId int64 `json:"userId"`
	// The campaign template name.
	Name string `json:"name"`
	// Customer-facing text that explains the objective of the template.
	Description string `json:"description"`
	// Customer-facing text that explains how to use the template. For example, you can use this property to explain the available attributes of this template, and how they can be modified when a user uses this template to create a new campaign.
	Instructions string `json:"instructions"`
	// The campaign attributes that campaigns created from this template will have by default.
	CampaignAttributes *map[string]interface{} `json:"campaignAttributes,omitempty"`
	// The campaign attributes that coupons created from this template will have by default.
	CouponAttributes *map[string]interface{} `json:"couponAttributes,omitempty"`
	// Only campaign templates in 'available' state may be used to create campaigns.
	State string `json:"state"`
	// The ID of the ruleset this campaign template will use.
	ActiveRulesetId *int64 `json:"activeRulesetId,omitempty"`
	// A list of tags for the campaign template.
	Tags *[]string `json:"tags,omitempty"`
	// A list of features for the campaign template.
	Features                  *[]string                                  `json:"features,omitempty"`
	CouponSettings            *CodeGeneratorSettings                     `json:"couponSettings,omitempty"`
	CouponReservationSettings *CampaignTemplateCouponReservationSettings `json:"couponReservationSettings,omitempty"`
	ReferralSettings          *CodeGeneratorSettings                     `json:"referralSettings,omitempty"`
	// The set of limits that operate for this campaign template.
	Limits *[]TemplateLimitConfig `json:"limits,omitempty"`
	// Fields which can be used to replace values in a rule.
	TemplateParams *[]CampaignTemplateParams `json:"templateParams,omitempty"`
	// A list of IDs of the Applications that are subscribed to this campaign template.
	ApplicationsIds []int64 `json:"applicationsIds"`
	// The campaign collections from the blueprint campaign for the template.
	CampaignCollections *[]CampaignTemplateCollection `json:"campaignCollections,omitempty"`
	// The default campaign group ID.
	DefaultCampaignGroupId *int64 `json:"defaultCampaignGroupId,omitempty"`
	// The campaign type. Possible type values:   - `cartItem`: Type of campaign that can apply effects only to cart items.   - `advanced`: Type of campaign that can apply effects to customer sessions and cart items.
	CampaignType string `json:"campaignType"`
	// The number of Campaigns created from this template.
	CampaignsCount *int64 `json:"campaignsCount,omitempty"`
	// Timestamp of the most recent update to the campaign template or any of its elements.
	Updated *time.Time `json:"updated,omitempty"`
	// Name of the user who last updated this campaign template, if available.
	UpdatedBy *string `json:"updatedBy,omitempty"`
	// The IDs of the Applications that are related to this entity.
	ValidApplicationIds []int64 `json:"validApplicationIds"`
	// A flag indicating whether the user marked the template as a favorite.
	IsUserFavorite *bool `json:"isUserFavorite,omitempty"`
}

// NewCampaignTemplate instantiates a new CampaignTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCampaignTemplate(id int64, created time.Time, accountId int64, userId int64, name string, description string, instructions string, state string, applicationsIds []int64, campaignType string, validApplicationIds []int64) *CampaignTemplate {
	this := CampaignTemplate{}
	this.Id = id
	this.Created = created
	this.AccountId = accountId
	this.UserId = userId
	this.Name = name
	this.Description = description
	this.Instructions = instructions
	this.State = state
	this.ApplicationsIds = applicationsIds
	this.CampaignType = campaignType
	this.ValidApplicationIds = validApplicationIds
	var isUserFavorite bool = false
	this.IsUserFavorite = &isUserFavorite
	return &this
}

// NewCampaignTemplateWithDefaults instantiates a new CampaignTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignTemplateWithDefaults() *CampaignTemplate {
	this := CampaignTemplate{}
	var campaignType string = "advanced"
	this.CampaignType = campaignType
	var isUserFavorite bool = false
	this.IsUserFavorite = &isUserFavorite
	return &this
}

// GetId returns the Id field value
func (o *CampaignTemplate) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CampaignTemplate) SetId(v int64) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *CampaignTemplate) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CampaignTemplate) SetCreated(v time.Time) {
	o.Created = v
}

// GetAccountId returns the AccountId field value
func (o *CampaignTemplate) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CampaignTemplate) SetAccountId(v int64) {
	o.AccountId = v
}

// GetUserId returns the UserId field value
func (o *CampaignTemplate) GetUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CampaignTemplate) SetUserId(v int64) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *CampaignTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CampaignTemplate) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CampaignTemplate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CampaignTemplate) SetDescription(v string) {
	o.Description = v
}

// GetInstructions returns the Instructions field value
func (o *CampaignTemplate) GetInstructions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instructions, true
}

// SetInstructions sets field value
func (o *CampaignTemplate) SetInstructions(v string) {
	o.Instructions = v
}

// GetCampaignAttributes returns the CampaignAttributes field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCampaignAttributes() map[string]interface{} {
	if o == nil || o.CampaignAttributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.CampaignAttributes
}

// GetCampaignAttributesOk returns a tuple with the CampaignAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCampaignAttributesOk() (*map[string]interface{}, bool) {
	if o == nil || o.CampaignAttributes == nil {
		return nil, false
	}
	return o.CampaignAttributes, true
}

// HasCampaignAttributes returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCampaignAttributes() bool {
	if o != nil && o.CampaignAttributes != nil {
		return true
	}

	return false
}

// SetCampaignAttributes gets a reference to the given map[string]interface{} and assigns it to the CampaignAttributes field.
func (o *CampaignTemplate) SetCampaignAttributes(v map[string]interface{}) {
	o.CampaignAttributes = &v
}

// GetCouponAttributes returns the CouponAttributes field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCouponAttributes() map[string]interface{} {
	if o == nil || o.CouponAttributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.CouponAttributes
}

// GetCouponAttributesOk returns a tuple with the CouponAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCouponAttributesOk() (*map[string]interface{}, bool) {
	if o == nil || o.CouponAttributes == nil {
		return nil, false
	}
	return o.CouponAttributes, true
}

// HasCouponAttributes returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCouponAttributes() bool {
	if o != nil && o.CouponAttributes != nil {
		return true
	}

	return false
}

// SetCouponAttributes gets a reference to the given map[string]interface{} and assigns it to the CouponAttributes field.
func (o *CampaignTemplate) SetCouponAttributes(v map[string]interface{}) {
	o.CouponAttributes = &v
}

// GetState returns the State field value
func (o *CampaignTemplate) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CampaignTemplate) SetState(v string) {
	o.State = v
}

// GetActiveRulesetId returns the ActiveRulesetId field value if set, zero value otherwise.
func (o *CampaignTemplate) GetActiveRulesetId() int64 {
	if o == nil || o.ActiveRulesetId == nil {
		var ret int64
		return ret
	}
	return *o.ActiveRulesetId
}

// GetActiveRulesetIdOk returns a tuple with the ActiveRulesetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetActiveRulesetIdOk() (*int64, bool) {
	if o == nil || o.ActiveRulesetId == nil {
		return nil, false
	}
	return o.ActiveRulesetId, true
}

// HasActiveRulesetId returns a boolean if a field has been set.
func (o *CampaignTemplate) HasActiveRulesetId() bool {
	if o != nil && o.ActiveRulesetId != nil {
		return true
	}

	return false
}

// SetActiveRulesetId gets a reference to the given int64 and assigns it to the ActiveRulesetId field.
func (o *CampaignTemplate) SetActiveRulesetId(v int64) {
	o.ActiveRulesetId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CampaignTemplate) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CampaignTemplate) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CampaignTemplate) SetTags(v []string) {
	o.Tags = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *CampaignTemplate) GetFeatures() []string {
	if o == nil || o.Features == nil {
		var ret []string
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetFeaturesOk() (*[]string, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *CampaignTemplate) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *CampaignTemplate) SetFeatures(v []string) {
	o.Features = &v
}

// GetCouponSettings returns the CouponSettings field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCouponSettings() CodeGeneratorSettings {
	if o == nil || o.CouponSettings == nil {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.CouponSettings
}

// GetCouponSettingsOk returns a tuple with the CouponSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCouponSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || o.CouponSettings == nil {
		return nil, false
	}
	return o.CouponSettings, true
}

// HasCouponSettings returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCouponSettings() bool {
	if o != nil && o.CouponSettings != nil {
		return true
	}

	return false
}

// SetCouponSettings gets a reference to the given CodeGeneratorSettings and assigns it to the CouponSettings field.
func (o *CampaignTemplate) SetCouponSettings(v CodeGeneratorSettings) {
	o.CouponSettings = &v
}

// GetCouponReservationSettings returns the CouponReservationSettings field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCouponReservationSettings() CampaignTemplateCouponReservationSettings {
	if o == nil || o.CouponReservationSettings == nil {
		var ret CampaignTemplateCouponReservationSettings
		return ret
	}
	return *o.CouponReservationSettings
}

// GetCouponReservationSettingsOk returns a tuple with the CouponReservationSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCouponReservationSettingsOk() (*CampaignTemplateCouponReservationSettings, bool) {
	if o == nil || o.CouponReservationSettings == nil {
		return nil, false
	}
	return o.CouponReservationSettings, true
}

// HasCouponReservationSettings returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCouponReservationSettings() bool {
	if o != nil && o.CouponReservationSettings != nil {
		return true
	}

	return false
}

// SetCouponReservationSettings gets a reference to the given CampaignTemplateCouponReservationSettings and assigns it to the CouponReservationSettings field.
func (o *CampaignTemplate) SetCouponReservationSettings(v CampaignTemplateCouponReservationSettings) {
	o.CouponReservationSettings = &v
}

// GetReferralSettings returns the ReferralSettings field value if set, zero value otherwise.
func (o *CampaignTemplate) GetReferralSettings() CodeGeneratorSettings {
	if o == nil || o.ReferralSettings == nil {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.ReferralSettings
}

// GetReferralSettingsOk returns a tuple with the ReferralSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetReferralSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || o.ReferralSettings == nil {
		return nil, false
	}
	return o.ReferralSettings, true
}

// HasReferralSettings returns a boolean if a field has been set.
func (o *CampaignTemplate) HasReferralSettings() bool {
	if o != nil && o.ReferralSettings != nil {
		return true
	}

	return false
}

// SetReferralSettings gets a reference to the given CodeGeneratorSettings and assigns it to the ReferralSettings field.
func (o *CampaignTemplate) SetReferralSettings(v CodeGeneratorSettings) {
	o.ReferralSettings = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *CampaignTemplate) GetLimits() []TemplateLimitConfig {
	if o == nil || o.Limits == nil {
		var ret []TemplateLimitConfig
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetLimitsOk() (*[]TemplateLimitConfig, bool) {
	if o == nil || o.Limits == nil {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *CampaignTemplate) HasLimits() bool {
	if o != nil && o.Limits != nil {
		return true
	}

	return false
}

// SetLimits gets a reference to the given []TemplateLimitConfig and assigns it to the Limits field.
func (o *CampaignTemplate) SetLimits(v []TemplateLimitConfig) {
	o.Limits = &v
}

// GetTemplateParams returns the TemplateParams field value if set, zero value otherwise.
func (o *CampaignTemplate) GetTemplateParams() []CampaignTemplateParams {
	if o == nil || o.TemplateParams == nil {
		var ret []CampaignTemplateParams
		return ret
	}
	return *o.TemplateParams
}

// GetTemplateParamsOk returns a tuple with the TemplateParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetTemplateParamsOk() (*[]CampaignTemplateParams, bool) {
	if o == nil || o.TemplateParams == nil {
		return nil, false
	}
	return o.TemplateParams, true
}

// HasTemplateParams returns a boolean if a field has been set.
func (o *CampaignTemplate) HasTemplateParams() bool {
	if o != nil && o.TemplateParams != nil {
		return true
	}

	return false
}

// SetTemplateParams gets a reference to the given []CampaignTemplateParams and assigns it to the TemplateParams field.
func (o *CampaignTemplate) SetTemplateParams(v []CampaignTemplateParams) {
	o.TemplateParams = &v
}

// GetApplicationsIds returns the ApplicationsIds field value
func (o *CampaignTemplate) GetApplicationsIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.ApplicationsIds
}

// GetApplicationsIdsOk returns a tuple with the ApplicationsIds field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetApplicationsIdsOk() (*[]int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationsIds, true
}

// SetApplicationsIds sets field value
func (o *CampaignTemplate) SetApplicationsIds(v []int64) {
	o.ApplicationsIds = v
}

// GetCampaignCollections returns the CampaignCollections field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCampaignCollections() []CampaignTemplateCollection {
	if o == nil || o.CampaignCollections == nil {
		var ret []CampaignTemplateCollection
		return ret
	}
	return *o.CampaignCollections
}

// GetCampaignCollectionsOk returns a tuple with the CampaignCollections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCampaignCollectionsOk() (*[]CampaignTemplateCollection, bool) {
	if o == nil || o.CampaignCollections == nil {
		return nil, false
	}
	return o.CampaignCollections, true
}

// HasCampaignCollections returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCampaignCollections() bool {
	if o != nil && o.CampaignCollections != nil {
		return true
	}

	return false
}

// SetCampaignCollections gets a reference to the given []CampaignTemplateCollection and assigns it to the CampaignCollections field.
func (o *CampaignTemplate) SetCampaignCollections(v []CampaignTemplateCollection) {
	o.CampaignCollections = &v
}

// GetDefaultCampaignGroupId returns the DefaultCampaignGroupId field value if set, zero value otherwise.
func (o *CampaignTemplate) GetDefaultCampaignGroupId() int64 {
	if o == nil || o.DefaultCampaignGroupId == nil {
		var ret int64
		return ret
	}
	return *o.DefaultCampaignGroupId
}

// GetDefaultCampaignGroupIdOk returns a tuple with the DefaultCampaignGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetDefaultCampaignGroupIdOk() (*int64, bool) {
	if o == nil || o.DefaultCampaignGroupId == nil {
		return nil, false
	}
	return o.DefaultCampaignGroupId, true
}

// HasDefaultCampaignGroupId returns a boolean if a field has been set.
func (o *CampaignTemplate) HasDefaultCampaignGroupId() bool {
	if o != nil && o.DefaultCampaignGroupId != nil {
		return true
	}

	return false
}

// SetDefaultCampaignGroupId gets a reference to the given int64 and assigns it to the DefaultCampaignGroupId field.
func (o *CampaignTemplate) SetDefaultCampaignGroupId(v int64) {
	o.DefaultCampaignGroupId = &v
}

// GetCampaignType returns the CampaignType field value
func (o *CampaignTemplate) GetCampaignType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignType
}

// GetCampaignTypeOk returns a tuple with the CampaignType field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCampaignTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignType, true
}

// SetCampaignType sets field value
func (o *CampaignTemplate) SetCampaignType(v string) {
	o.CampaignType = v
}

// GetCampaignsCount returns the CampaignsCount field value if set, zero value otherwise.
func (o *CampaignTemplate) GetCampaignsCount() int64 {
	if o == nil || o.CampaignsCount == nil {
		var ret int64
		return ret
	}
	return *o.CampaignsCount
}

// GetCampaignsCountOk returns a tuple with the CampaignsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetCampaignsCountOk() (*int64, bool) {
	if o == nil || o.CampaignsCount == nil {
		return nil, false
	}
	return o.CampaignsCount, true
}

// HasCampaignsCount returns a boolean if a field has been set.
func (o *CampaignTemplate) HasCampaignsCount() bool {
	if o != nil && o.CampaignsCount != nil {
		return true
	}

	return false
}

// SetCampaignsCount gets a reference to the given int64 and assigns it to the CampaignsCount field.
func (o *CampaignTemplate) SetCampaignsCount(v int64) {
	o.CampaignsCount = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *CampaignTemplate) GetUpdated() time.Time {
	if o == nil || o.Updated == nil {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || o.Updated == nil {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *CampaignTemplate) HasUpdated() bool {
	if o != nil && o.Updated != nil {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *CampaignTemplate) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *CampaignTemplate) GetUpdatedBy() string {
	if o == nil || o.UpdatedBy == nil {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetUpdatedByOk() (*string, bool) {
	if o == nil || o.UpdatedBy == nil {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *CampaignTemplate) HasUpdatedBy() bool {
	if o != nil && o.UpdatedBy != nil {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *CampaignTemplate) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetValidApplicationIds returns the ValidApplicationIds field value
func (o *CampaignTemplate) GetValidApplicationIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.ValidApplicationIds
}

// GetValidApplicationIdsOk returns a tuple with the ValidApplicationIds field value
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetValidApplicationIdsOk() (*[]int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidApplicationIds, true
}

// SetValidApplicationIds sets field value
func (o *CampaignTemplate) SetValidApplicationIds(v []int64) {
	o.ValidApplicationIds = v
}

// GetIsUserFavorite returns the IsUserFavorite field value if set, zero value otherwise.
func (o *CampaignTemplate) GetIsUserFavorite() bool {
	if o == nil || o.IsUserFavorite == nil {
		var ret bool
		return ret
	}
	return *o.IsUserFavorite
}

// GetIsUserFavoriteOk returns a tuple with the IsUserFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplate) GetIsUserFavoriteOk() (*bool, bool) {
	if o == nil || o.IsUserFavorite == nil {
		return nil, false
	}
	return o.IsUserFavorite, true
}

// HasIsUserFavorite returns a boolean if a field has been set.
func (o *CampaignTemplate) HasIsUserFavorite() bool {
	if o != nil && o.IsUserFavorite != nil {
		return true
	}

	return false
}

// SetIsUserFavorite gets a reference to the given bool and assigns it to the IsUserFavorite field.
func (o *CampaignTemplate) SetIsUserFavorite(v bool) {
	o.IsUserFavorite = &v
}

func (o CampaignTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["instructions"] = o.Instructions
	}
	if o.CampaignAttributes != nil {
		toSerialize["campaignAttributes"] = o.CampaignAttributes
	}
	if o.CouponAttributes != nil {
		toSerialize["couponAttributes"] = o.CouponAttributes
	}
	if true {
		toSerialize["state"] = o.State
	}
	if o.ActiveRulesetId != nil {
		toSerialize["activeRulesetId"] = o.ActiveRulesetId
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	if o.CouponSettings != nil {
		toSerialize["couponSettings"] = o.CouponSettings
	}
	if o.CouponReservationSettings != nil {
		toSerialize["couponReservationSettings"] = o.CouponReservationSettings
	}
	if o.ReferralSettings != nil {
		toSerialize["referralSettings"] = o.ReferralSettings
	}
	if o.Limits != nil {
		toSerialize["limits"] = o.Limits
	}
	if o.TemplateParams != nil {
		toSerialize["templateParams"] = o.TemplateParams
	}
	if true {
		toSerialize["applicationsIds"] = o.ApplicationsIds
	}
	if o.CampaignCollections != nil {
		toSerialize["campaignCollections"] = o.CampaignCollections
	}
	if o.DefaultCampaignGroupId != nil {
		toSerialize["defaultCampaignGroupId"] = o.DefaultCampaignGroupId
	}
	if true {
		toSerialize["campaignType"] = o.CampaignType
	}
	if o.CampaignsCount != nil {
		toSerialize["campaignsCount"] = o.CampaignsCount
	}
	if o.Updated != nil {
		toSerialize["updated"] = o.Updated
	}
	if o.UpdatedBy != nil {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if true {
		toSerialize["validApplicationIds"] = o.ValidApplicationIds
	}
	if o.IsUserFavorite != nil {
		toSerialize["isUserFavorite"] = o.IsUserFavorite
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignTemplate struct {
	value *CampaignTemplate
	isSet bool
}

func (v NullableCampaignTemplate) Get() *CampaignTemplate {
	return v.value
}

func (v *NullableCampaignTemplate) Set(val *CampaignTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCampaignTemplate(val *CampaignTemplate) *NullableCampaignTemplate {
	return &NullableCampaignTemplate{value: val, isSet: true}
}

func (v NullableCampaignTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
