/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
	"time"
)

// CustomerSessionAllOf struct for CustomerSessionAllOf
type CustomerSessionAllOf struct {
	// Indicates whether this is the first session for the customer's profile. Will always be true for anonymous sessions.
	FirstSession bool `json:"firstSession"`
	// A map of labelled discount values, values will be in the same currency as the application associated with the session.
	Discounts map[string]float32 `json:"discounts"`
	IntegrationId string `json:"integrationId"`
	// Timestamp of the most recent event received on this session.
	Updated time.Time `json:"updated"`
}

// GetFirstSession returns the FirstSession field value
func (o *CustomerSessionAllOf) GetFirstSession() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FirstSession
}

// SetFirstSession sets field value
func (o *CustomerSessionAllOf) SetFirstSession(v bool) {
	o.FirstSession = v
}

// GetDiscounts returns the Discounts field value
func (o *CustomerSessionAllOf) GetDiscounts() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.Discounts
}

// SetDiscounts sets field value
func (o *CustomerSessionAllOf) SetDiscounts(v map[string]float32) {
	o.Discounts = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *CustomerSessionAllOf) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// SetIntegrationId sets field value
func (o *CustomerSessionAllOf) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetUpdated returns the Updated field value
func (o *CustomerSessionAllOf) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// SetUpdated sets field value
func (o *CustomerSessionAllOf) SetUpdated(v time.Time) {
	o.Updated = v
}

type NullableCustomerSessionAllOf struct {
	Value CustomerSessionAllOf
	ExplicitNull bool
}

func (v NullableCustomerSessionAllOf) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableCustomerSessionAllOf) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
