/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// OutgoingIntegrationTemplateWithConfigurationDetailsAllOf struct for OutgoingIntegrationTemplateWithConfigurationDetailsAllOf
type OutgoingIntegrationTemplateWithConfigurationDetailsAllOf struct {
	Policy OutgoingIntegrationConfigurationPolicy `json:"policy"`
}

// GetPolicy returns the Policy field value
func (o *OutgoingIntegrationTemplateWithConfigurationDetailsAllOf) GetPolicy() OutgoingIntegrationConfigurationPolicy {
	if o == nil {
		var ret OutgoingIntegrationConfigurationPolicy
		return ret
	}

	return o.Policy
}

// SetPolicy sets field value
func (o *OutgoingIntegrationTemplateWithConfigurationDetailsAllOf) SetPolicy(v OutgoingIntegrationConfigurationPolicy) {
	o.Policy = v
}

type NullableOutgoingIntegrationTemplateWithConfigurationDetailsAllOf struct {
	Value OutgoingIntegrationTemplateWithConfigurationDetailsAllOf
	ExplicitNull bool
}

func (v NullableOutgoingIntegrationTemplateWithConfigurationDetailsAllOf) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableOutgoingIntegrationTemplateWithConfigurationDetailsAllOf) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
