/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// NewCustomerProfile struct for NewCustomerProfile
type NewCustomerProfile struct {
	// Arbitrary properties associated with this item.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
}

// NewNewCustomerProfile instantiates a new NewCustomerProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildNewCustomerProfile() *NewCustomerProfile {
	this := NewCustomerProfile{}
	return &this
}

// NewNewCustomerProfileWithDefaults instantiates a new NewCustomerProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewCustomerProfileWithDefaults() *NewCustomerProfile {
	this := NewCustomerProfile{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *NewCustomerProfile) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCustomerProfile) GetAttributesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *NewCustomerProfile) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *NewCustomerProfile) SetAttributes(v map[string]interface{}) {
	o.Attributes = &v
}

func (o NewCustomerProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableNewCustomerProfile struct {
	value *NewCustomerProfile
	isSet bool
}

func (v NullableNewCustomerProfile) Get() *NewCustomerProfile {
	return v.value
}

func (v *NullableNewCustomerProfile) Set(val *NewCustomerProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableNewCustomerProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableNewCustomerProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableNewCustomerProfile(val *NewCustomerProfile) *NullableNewCustomerProfile {
	return &NullableNewCustomerProfile{value: val, isSet: true}
}

func (v NullableNewCustomerProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewCustomerProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
