/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// SetLoyaltyPointsExpiryDateEffectProps The properties specific to the \"setLoyaltyPointsExpiryDate\" effect. This gets triggered when a validated rule contains the \"set expiry date\" effect. The current expiry date gets set to the date given in the effect.
type SetLoyaltyPointsExpiryDateEffectProps struct {
	// ID of the loyalty program that contains these points.
	ProgramId int64 `json:"programId"`
	// API name of the loyalty program subledger that contains these points.
	SubLedgerId string `json:"subLedgerId"`
	// The specified expiry date and time for all active and pending point transactions in the loyalty program subledger.
	NewExpiryDate time.Time `json:"newExpiryDate"`
	// List of transactions affected by the expiry date update.
	AffectedTransactions *[]LoyaltyLedgerEntryExpiryDateChange `json:"affectedTransactions,omitempty"`
}

// NewSetLoyaltyPointsExpiryDateEffectProps instantiates a new SetLoyaltyPointsExpiryDateEffectProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildSetLoyaltyPointsExpiryDateEffectProps(programId int64, subLedgerId string, newExpiryDate time.Time) *SetLoyaltyPointsExpiryDateEffectProps {
	this := SetLoyaltyPointsExpiryDateEffectProps{}
	this.ProgramId = programId
	this.SubLedgerId = subLedgerId
	this.NewExpiryDate = newExpiryDate
	return &this
}

// NewSetLoyaltyPointsExpiryDateEffectPropsWithDefaults instantiates a new SetLoyaltyPointsExpiryDateEffectProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLoyaltyPointsExpiryDateEffectPropsWithDefaults() *SetLoyaltyPointsExpiryDateEffectProps {
	this := SetLoyaltyPointsExpiryDateEffectProps{}
	return &this
}

// GetProgramId returns the ProgramId field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetProgramId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProgramId
}

// GetProgramIdOk returns a tuple with the ProgramId field value
// and a boolean to check if the value has been set.
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetProgramIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProgramId, true
}

// SetProgramId sets field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) SetProgramId(v int64) {
	o.ProgramId = v
}

// GetSubLedgerId returns the SubLedgerId field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetSubLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubLedgerId
}

// GetSubLedgerIdOk returns a tuple with the SubLedgerId field value
// and a boolean to check if the value has been set.
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetSubLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubLedgerId, true
}

// SetSubLedgerId sets field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) SetSubLedgerId(v string) {
	o.SubLedgerId = v
}

// GetNewExpiryDate returns the NewExpiryDate field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetNewExpiryDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.NewExpiryDate
}

// GetNewExpiryDateOk returns a tuple with the NewExpiryDate field value
// and a boolean to check if the value has been set.
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetNewExpiryDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewExpiryDate, true
}

// SetNewExpiryDate sets field value
func (o *SetLoyaltyPointsExpiryDateEffectProps) SetNewExpiryDate(v time.Time) {
	o.NewExpiryDate = v
}

// GetAffectedTransactions returns the AffectedTransactions field value if set, zero value otherwise.
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetAffectedTransactions() []LoyaltyLedgerEntryExpiryDateChange {
	if o == nil || o.AffectedTransactions == nil {
		var ret []LoyaltyLedgerEntryExpiryDateChange
		return ret
	}
	return *o.AffectedTransactions
}

// GetAffectedTransactionsOk returns a tuple with the AffectedTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetLoyaltyPointsExpiryDateEffectProps) GetAffectedTransactionsOk() (*[]LoyaltyLedgerEntryExpiryDateChange, bool) {
	if o == nil || o.AffectedTransactions == nil {
		return nil, false
	}
	return o.AffectedTransactions, true
}

// HasAffectedTransactions returns a boolean if a field has been set.
func (o *SetLoyaltyPointsExpiryDateEffectProps) HasAffectedTransactions() bool {
	if o != nil && o.AffectedTransactions != nil {
		return true
	}

	return false
}

// SetAffectedTransactions gets a reference to the given []LoyaltyLedgerEntryExpiryDateChange and assigns it to the AffectedTransactions field.
func (o *SetLoyaltyPointsExpiryDateEffectProps) SetAffectedTransactions(v []LoyaltyLedgerEntryExpiryDateChange) {
	o.AffectedTransactions = &v
}

func (o SetLoyaltyPointsExpiryDateEffectProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["programId"] = o.ProgramId
	}
	if true {
		toSerialize["subLedgerId"] = o.SubLedgerId
	}
	if true {
		toSerialize["newExpiryDate"] = o.NewExpiryDate
	}
	if o.AffectedTransactions != nil {
		toSerialize["affectedTransactions"] = o.AffectedTransactions
	}
	return json.Marshal(toSerialize)
}

type NullableSetLoyaltyPointsExpiryDateEffectProps struct {
	value *SetLoyaltyPointsExpiryDateEffectProps
	isSet bool
}

func (v NullableSetLoyaltyPointsExpiryDateEffectProps) Get() *SetLoyaltyPointsExpiryDateEffectProps {
	return v.value
}

func (v *NullableSetLoyaltyPointsExpiryDateEffectProps) Set(val *SetLoyaltyPointsExpiryDateEffectProps) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLoyaltyPointsExpiryDateEffectProps) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLoyaltyPointsExpiryDateEffectProps) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableSetLoyaltyPointsExpiryDateEffectProps(val *SetLoyaltyPointsExpiryDateEffectProps) *NullableSetLoyaltyPointsExpiryDateEffectProps {
	return &NullableSetLoyaltyPointsExpiryDateEffectProps{value: val, isSet: true}
}

func (v NullableSetLoyaltyPointsExpiryDateEffectProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLoyaltyPointsExpiryDateEffectProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
