/*
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// SetDiscountPerAdditionalCostEffectProps The properties specific to the \"setDiscountPerAdditionalCost\" effect. This gets triggered whenever a validated rule contained a \"set per additional cost discount\" effect. This is a discount that should be applied on a specific additional cost.
type SetDiscountPerAdditionalCostEffectProps struct {
	// The name/description of this discount
	Name string `json:"name"`
	// The ID of the additional cost
	AdditionalCostId int32 `json:"additionalCostId"`
	// The name of the additional cost
	AdditionalCost string `json:"additionalCost"`
	// The total monetary value of the discount
	Value float32 `json:"value"`
}

// GetName returns the Name field value
func (o *SetDiscountPerAdditionalCostEffectProps) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value
func (o *SetDiscountPerAdditionalCostEffectProps) SetName(v string) {
	o.Name = v
}

// GetAdditionalCostId returns the AdditionalCostId field value
func (o *SetDiscountPerAdditionalCostEffectProps) GetAdditionalCostId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AdditionalCostId
}

// SetAdditionalCostId sets field value
func (o *SetDiscountPerAdditionalCostEffectProps) SetAdditionalCostId(v int32) {
	o.AdditionalCostId = v
}

// GetAdditionalCost returns the AdditionalCost field value
func (o *SetDiscountPerAdditionalCostEffectProps) GetAdditionalCost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdditionalCost
}

// SetAdditionalCost sets field value
func (o *SetDiscountPerAdditionalCostEffectProps) SetAdditionalCost(v string) {
	o.AdditionalCost = v
}

// GetValue returns the Value field value
func (o *SetDiscountPerAdditionalCostEffectProps) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// SetValue sets field value
func (o *SetDiscountPerAdditionalCostEffectProps) SetValue(v float32) {
	o.Value = v
}

type NullableSetDiscountPerAdditionalCostEffectProps struct {
	Value        SetDiscountPerAdditionalCostEffectProps
	ExplicitNull bool
}

func (v NullableSetDiscountPerAdditionalCostEffectProps) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableSetDiscountPerAdditionalCostEffectProps) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
