/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// InfluencingCampaignDetails Details about a campaign that influenced the final price.
type InfluencingCampaignDetails struct {
	// Identifier of the campaign that influenced the final price.
	CampaignId int64 `json:"campaignId"`
	// Discount value applied by the campaign.
	DiscountValue float32 `json:"discountValue"`
}

// NewInfluencingCampaignDetails instantiates a new InfluencingCampaignDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildInfluencingCampaignDetails(campaignId int64, discountValue float32) *InfluencingCampaignDetails {
	this := InfluencingCampaignDetails{}
	this.CampaignId = campaignId
	this.DiscountValue = discountValue
	return &this
}

// NewInfluencingCampaignDetailsWithDefaults instantiates a new InfluencingCampaignDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfluencingCampaignDetailsWithDefaults() *InfluencingCampaignDetails {
	this := InfluencingCampaignDetails{}
	return &this
}

// GetCampaignId returns the CampaignId field value
func (o *InfluencingCampaignDetails) GetCampaignId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *InfluencingCampaignDetails) GetCampaignIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *InfluencingCampaignDetails) SetCampaignId(v int64) {
	o.CampaignId = v
}

// GetDiscountValue returns the DiscountValue field value
func (o *InfluencingCampaignDetails) GetDiscountValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DiscountValue
}

// GetDiscountValueOk returns a tuple with the DiscountValue field value
// and a boolean to check if the value has been set.
func (o *InfluencingCampaignDetails) GetDiscountValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountValue, true
}

// SetDiscountValue sets field value
func (o *InfluencingCampaignDetails) SetDiscountValue(v float32) {
	o.DiscountValue = v
}

func (o InfluencingCampaignDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["campaignId"] = o.CampaignId
	}
	if true {
		toSerialize["discountValue"] = o.DiscountValue
	}
	return json.Marshal(toSerialize)
}

type NullableInfluencingCampaignDetails struct {
	value *InfluencingCampaignDetails
	isSet bool
}

func (v NullableInfluencingCampaignDetails) Get() *InfluencingCampaignDetails {
	return v.value
}

func (v *NullableInfluencingCampaignDetails) Set(val *InfluencingCampaignDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableInfluencingCampaignDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableInfluencingCampaignDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableInfluencingCampaignDetails(val *InfluencingCampaignDetails) *NullableInfluencingCampaignDetails {
	return &NullableInfluencingCampaignDetails{value: val, isSet: true}
}

func (v NullableInfluencingCampaignDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfluencingCampaignDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
