/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// GenerateCampaignSummary struct for GenerateCampaignSummary
type GenerateCampaignSummary struct {
	// ID of a campaign.
	CampaignID int64 `json:"campaignID"`
	// ID of a ruleset.
	RulesetID int64 `json:"rulesetID"`
	// Currency for the campaign.
	Currency string `json:"currency"`
}

// NewGenerateCampaignSummary instantiates a new GenerateCampaignSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildGenerateCampaignSummary(campaignID int64, rulesetID int64, currency string) *GenerateCampaignSummary {
	this := GenerateCampaignSummary{}
	this.CampaignID = campaignID
	this.RulesetID = rulesetID
	this.Currency = currency
	return &this
}

// NewGenerateCampaignSummaryWithDefaults instantiates a new GenerateCampaignSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateCampaignSummaryWithDefaults() *GenerateCampaignSummary {
	this := GenerateCampaignSummary{}
	return &this
}

// GetCampaignID returns the CampaignID field value
func (o *GenerateCampaignSummary) GetCampaignID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CampaignID
}

// GetCampaignIDOk returns a tuple with the CampaignID field value
// and a boolean to check if the value has been set.
func (o *GenerateCampaignSummary) GetCampaignIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignID, true
}

// SetCampaignID sets field value
func (o *GenerateCampaignSummary) SetCampaignID(v int64) {
	o.CampaignID = v
}

// GetRulesetID returns the RulesetID field value
func (o *GenerateCampaignSummary) GetRulesetID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RulesetID
}

// GetRulesetIDOk returns a tuple with the RulesetID field value
// and a boolean to check if the value has been set.
func (o *GenerateCampaignSummary) GetRulesetIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RulesetID, true
}

// SetRulesetID sets field value
func (o *GenerateCampaignSummary) SetRulesetID(v int64) {
	o.RulesetID = v
}

// GetCurrency returns the Currency field value
func (o *GenerateCampaignSummary) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GenerateCampaignSummary) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GenerateCampaignSummary) SetCurrency(v string) {
	o.Currency = v
}

func (o GenerateCampaignSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["campaignID"] = o.CampaignID
	}
	if true {
		toSerialize["rulesetID"] = o.RulesetID
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateCampaignSummary struct {
	value *GenerateCampaignSummary
	isSet bool
}

func (v NullableGenerateCampaignSummary) Get() *GenerateCampaignSummary {
	return v.value
}

func (v *NullableGenerateCampaignSummary) Set(val *GenerateCampaignSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateCampaignSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateCampaignSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableGenerateCampaignSummary(val *GenerateCampaignSummary) *NullableGenerateCampaignSummary {
	return &NullableGenerateCampaignSummary{value: val, isSet: true}
}

func (v NullableGenerateCampaignSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateCampaignSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
