/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// AccountEntity struct for AccountEntity
type AccountEntity struct {
	// The ID of the account that owns this entity.
	AccountId int64 `json:"accountId"`
}

// NewAccountEntity instantiates a new AccountEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildAccountEntity(accountId int64) *AccountEntity {
	this := AccountEntity{}
	this.AccountId = accountId
	return &this
}

// NewAccountEntityWithDefaults instantiates a new AccountEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountEntityWithDefaults() *AccountEntity {
	this := AccountEntity{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccountEntity) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountEntity) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountEntity) SetAccountId(v int64) {
	o.AccountId = v
}

func (o AccountEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAccountEntity struct {
	value *AccountEntity
	isSet bool
}

func (v NullableAccountEntity) Get() *AccountEntity {
	return v.value
}

func (v *NullableAccountEntity) Set(val *AccountEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableAccountEntity(val *AccountEntity) *NullableAccountEntity {
	return &NullableAccountEntity{value: val, isSet: true}
}

func (v NullableAccountEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
