/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// ScimSchemasListResponse List of resource schemas supported by the SCIM provisioning protocol.
type ScimSchemasListResponse struct {
	Resources []ScimSchemaResource `json:"Resources"`
	// SCIM schema for the given resource.
	Schemas *[]string `json:"schemas,omitempty"`
	// Number of total results in the response.
	TotalResults *int64 `json:"totalResults,omitempty"`
}

// NewScimSchemasListResponse instantiates a new ScimSchemasListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildScimSchemasListResponse(resources []ScimSchemaResource) *ScimSchemasListResponse {
	this := ScimSchemasListResponse{}
	this.Resources = resources
	return &this
}

// NewScimSchemasListResponseWithDefaults instantiates a new ScimSchemasListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimSchemasListResponseWithDefaults() *ScimSchemasListResponse {
	this := ScimSchemasListResponse{}
	return &this
}

// GetResources returns the Resources field value
func (o *ScimSchemasListResponse) GetResources() []ScimSchemaResource {
	if o == nil {
		var ret []ScimSchemaResource
		return ret
	}

	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value
// and a boolean to check if the value has been set.
func (o *ScimSchemasListResponse) GetResourcesOk() (*[]ScimSchemaResource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resources, true
}

// SetResources sets field value
func (o *ScimSchemasListResponse) SetResources(v []ScimSchemaResource) {
	o.Resources = v
}

// GetSchemas returns the Schemas field value if set, zero value otherwise.
func (o *ScimSchemasListResponse) GetSchemas() []string {
	if o == nil || o.Schemas == nil {
		var ret []string
		return ret
	}
	return *o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimSchemasListResponse) GetSchemasOk() (*[]string, bool) {
	if o == nil || o.Schemas == nil {
		return nil, false
	}
	return o.Schemas, true
}

// HasSchemas returns a boolean if a field has been set.
func (o *ScimSchemasListResponse) HasSchemas() bool {
	if o != nil && o.Schemas != nil {
		return true
	}

	return false
}

// SetSchemas gets a reference to the given []string and assigns it to the Schemas field.
func (o *ScimSchemasListResponse) SetSchemas(v []string) {
	o.Schemas = &v
}

// GetTotalResults returns the TotalResults field value if set, zero value otherwise.
func (o *ScimSchemasListResponse) GetTotalResults() int64 {
	if o == nil || o.TotalResults == nil {
		var ret int64
		return ret
	}
	return *o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimSchemasListResponse) GetTotalResultsOk() (*int64, bool) {
	if o == nil || o.TotalResults == nil {
		return nil, false
	}
	return o.TotalResults, true
}

// HasTotalResults returns a boolean if a field has been set.
func (o *ScimSchemasListResponse) HasTotalResults() bool {
	if o != nil && o.TotalResults != nil {
		return true
	}

	return false
}

// SetTotalResults gets a reference to the given int64 and assigns it to the TotalResults field.
func (o *ScimSchemasListResponse) SetTotalResults(v int64) {
	o.TotalResults = &v
}

func (o ScimSchemasListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Resources"] = o.Resources
	}
	if o.Schemas != nil {
		toSerialize["schemas"] = o.Schemas
	}
	if o.TotalResults != nil {
		toSerialize["totalResults"] = o.TotalResults
	}
	return json.Marshal(toSerialize)
}

type NullableScimSchemasListResponse struct {
	value *ScimSchemasListResponse
	isSet bool
}

func (v NullableScimSchemasListResponse) Get() *ScimSchemasListResponse {
	return v.value
}

func (v *NullableScimSchemasListResponse) Set(val *ScimSchemasListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScimSchemasListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScimSchemasListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableScimSchemasListResponse(val *ScimSchemasListResponse) *NullableScimSchemasListResponse {
	return &NullableScimSchemasListResponse{value: val, isSet: true}
}

func (v NullableScimSchemasListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimSchemasListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
