/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// CampaignCreatedNotification struct for CampaignCreatedNotification
type CampaignCreatedNotification struct {
	// The type of the notification
	NotificationType string `json:"NotificationType"`
	// The total size of the result set.
	TotalResultSize int64 `json:"TotalResultSize"`
	// A list of campaign notification data.
	Data *[]CampaignCreatedNotificationItem `json:"Data,omitempty"`
}

// NewCampaignCreatedNotification instantiates a new CampaignCreatedNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCampaignCreatedNotification(notificationType string, totalResultSize int64) *CampaignCreatedNotification {
	this := CampaignCreatedNotification{}
	this.NotificationType = notificationType
	this.TotalResultSize = totalResultSize
	return &this
}

// NewCampaignCreatedNotificationWithDefaults instantiates a new CampaignCreatedNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignCreatedNotificationWithDefaults() *CampaignCreatedNotification {
	this := CampaignCreatedNotification{}
	return &this
}

// GetNotificationType returns the NotificationType field value
func (o *CampaignCreatedNotification) GetNotificationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationType
}

// GetNotificationTypeOk returns a tuple with the NotificationType field value
// and a boolean to check if the value has been set.
func (o *CampaignCreatedNotification) GetNotificationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationType, true
}

// SetNotificationType sets field value
func (o *CampaignCreatedNotification) SetNotificationType(v string) {
	o.NotificationType = v
}

// GetTotalResultSize returns the TotalResultSize field value
func (o *CampaignCreatedNotification) GetTotalResultSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalResultSize
}

// GetTotalResultSizeOk returns a tuple with the TotalResultSize field value
// and a boolean to check if the value has been set.
func (o *CampaignCreatedNotification) GetTotalResultSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalResultSize, true
}

// SetTotalResultSize sets field value
func (o *CampaignCreatedNotification) SetTotalResultSize(v int64) {
	o.TotalResultSize = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CampaignCreatedNotification) GetData() []CampaignCreatedNotificationItem {
	if o == nil || o.Data == nil {
		var ret []CampaignCreatedNotificationItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignCreatedNotification) GetDataOk() (*[]CampaignCreatedNotificationItem, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CampaignCreatedNotification) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []CampaignCreatedNotificationItem and assigns it to the Data field.
func (o *CampaignCreatedNotification) SetData(v []CampaignCreatedNotificationItem) {
	o.Data = &v
}

func (o CampaignCreatedNotification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["NotificationType"] = o.NotificationType
	}
	if true {
		toSerialize["TotalResultSize"] = o.TotalResultSize
	}
	if o.Data != nil {
		toSerialize["Data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignCreatedNotification struct {
	value *CampaignCreatedNotification
	isSet bool
}

func (v NullableCampaignCreatedNotification) Get() *CampaignCreatedNotification {
	return v.value
}

func (v *NullableCampaignCreatedNotification) Set(val *CampaignCreatedNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignCreatedNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignCreatedNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCampaignCreatedNotification(val *CampaignCreatedNotification) *NullableCampaignCreatedNotification {
	return &NullableCampaignCreatedNotification{value: val, isSet: true}
}

func (v NullableCampaignCreatedNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignCreatedNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
