/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"bytes"
	"encoding/json"
)

// ListCampaignStoreBudgets struct for ListCampaignStoreBudgets
type ListCampaignStoreBudgets struct {
	Store  ListCampaignStoreBudgetsStore `json:"store"`
	Limit  int32                         `json:"limit"`
	Action string                        `json:"action"`
	Period *string                       `json:"period,omitempty"`
}

// GetStore returns the Store field value
func (o *ListCampaignStoreBudgets) GetStore() ListCampaignStoreBudgetsStore {
	if o == nil {
		var ret ListCampaignStoreBudgetsStore
		return ret
	}

	return o.Store
}

// SetStore sets field value
func (o *ListCampaignStoreBudgets) SetStore(v ListCampaignStoreBudgetsStore) {
	o.Store = v
}

// GetLimit returns the Limit field value
func (o *ListCampaignStoreBudgets) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// SetLimit sets field value
func (o *ListCampaignStoreBudgets) SetLimit(v int32) {
	o.Limit = v
}

// GetAction returns the Action field value
func (o *ListCampaignStoreBudgets) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// SetAction sets field value
func (o *ListCampaignStoreBudgets) SetAction(v string) {
	o.Action = v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *ListCampaignStoreBudgets) GetPeriod() string {
	if o == nil || o.Period == nil {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *ListCampaignStoreBudgets) GetPeriodOk() (string, bool) {
	if o == nil || o.Period == nil {
		var ret string
		return ret, false
	}
	return *o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *ListCampaignStoreBudgets) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *ListCampaignStoreBudgets) SetPeriod(v string) {
	o.Period = &v
}

type NullableListCampaignStoreBudgets struct {
	Value        ListCampaignStoreBudgets
	ExplicitNull bool
}

func (v NullableListCampaignStoreBudgets) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableListCampaignStoreBudgets) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
