/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// LocationCheckAttributeBlock A block variant of `CheckAttributeBlock` for operators that check whether a geographical location is inside a set of geometric areas.
type LocationCheckAttributeBlock struct {
	// The location membership operator applied to the attribute.
	Operator *string `json:"operator,omitempty"`
	// The geometric areas to check the location against.
	Values map[string]interface{} `json:"values"`
}

// NewLocationCheckAttributeBlock instantiates a new LocationCheckAttributeBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildLocationCheckAttributeBlock(values map[string]interface{}) *LocationCheckAttributeBlock {
	this := LocationCheckAttributeBlock{}
	this.Values = values
	return &this
}

// NewLocationCheckAttributeBlockWithDefaults instantiates a new LocationCheckAttributeBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationCheckAttributeBlockWithDefaults() *LocationCheckAttributeBlock {
	this := LocationCheckAttributeBlock{}
	return &this
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *LocationCheckAttributeBlock) GetOperator() string {
	if o == nil || o.Operator == nil {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationCheckAttributeBlock) GetOperatorOk() (*string, bool) {
	if o == nil || o.Operator == nil {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *LocationCheckAttributeBlock) HasOperator() bool {
	if o != nil && o.Operator != nil {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *LocationCheckAttributeBlock) SetOperator(v string) {
	o.Operator = &v
}

// GetValues returns the Values field value
func (o *LocationCheckAttributeBlock) GetValues() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *LocationCheckAttributeBlock) GetValuesOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Values, true
}

// SetValues sets field value
func (o *LocationCheckAttributeBlock) SetValues(v map[string]interface{}) {
	o.Values = v
}

func (o LocationCheckAttributeBlock) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Operator != nil {
		toSerialize["operator"] = o.Operator
	}
	if true {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableLocationCheckAttributeBlock struct {
	value *LocationCheckAttributeBlock
	isSet bool
}

func (v NullableLocationCheckAttributeBlock) Get() *LocationCheckAttributeBlock {
	return v.value
}

func (v *NullableLocationCheckAttributeBlock) Set(val *LocationCheckAttributeBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationCheckAttributeBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationCheckAttributeBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableLocationCheckAttributeBlock(val *LocationCheckAttributeBlock) *NullableLocationCheckAttributeBlock {
	return &NullableLocationCheckAttributeBlock{value: val, isSet: true}
}

func (v NullableLocationCheckAttributeBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationCheckAttributeBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
