/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
	"time"
)

// CampaignEligibility A list of campaigns and their evaluation status for the current customer session.  For experiment campaigns, the experiment and variant assigned to the customer profile are returned through the `experiment` field. Customer profiles with no variant assignment are not included.  **Note**:  - This response can **only** be included if the `dry` parameter in the query is set to `true`.  - Do not include `triggeredCampaigns` or `ruleFailureReasons` in `responseContent` to avoid duplicate results.
type CampaignEligibility struct {
	// The ID of the Application that owns this entity.
	ApplicationId int64 `json:"applicationId"`
	// Unique ID of Campaign.
	Id int64 `json:"id"`
	// The name of the campaign.
	Name string `json:"name"`
	// A detailed description of the campaign.
	Description *string `json:"description,omitempty"`
	// Timestamp when the campaign will become active.
	StartTime *time.Time `json:"startTime,omitempty"`
	// Timestamp when the campaign will become inactive.
	EndTime *time.Time `json:"endTime,omitempty"`
	// Arbitrary properties associated with this campaign.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	// The state of the campaign.
	State string `json:"state"`
	// A list of tags for the campaign.
	Tags []string `json:"tags"`
	// The features enabled in this campaign.
	Features []string `json:"features"`
	// The customer's eligibility for each campaign in the current customer session.
	Eligibility []CampaignEligibilityDetails `json:"eligibility"`
	// A list of rules containing customer-facing details of the rewards defined in the campaign.
	Rules      []RuleMetadataEligibility      `json:"rules"`
	Experiment *CampaignEligibilityExperiment `json:"experiment,omitempty"`
}

// NewCampaignEligibility instantiates a new CampaignEligibility object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCampaignEligibility(applicationId int64, id int64, name string, state string, tags []string, features []string, eligibility []CampaignEligibilityDetails, rules []RuleMetadataEligibility) *CampaignEligibility {
	this := CampaignEligibility{}
	this.ApplicationId = applicationId
	this.Id = id
	this.Name = name
	this.State = state
	this.Tags = tags
	this.Features = features
	this.Eligibility = eligibility
	this.Rules = rules
	return &this
}

// NewCampaignEligibilityWithDefaults instantiates a new CampaignEligibility object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignEligibilityWithDefaults() *CampaignEligibility {
	this := CampaignEligibility{}
	var state string = "enabled"
	this.State = state
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *CampaignEligibility) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *CampaignEligibility) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetId returns the Id field value
func (o *CampaignEligibility) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CampaignEligibility) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CampaignEligibility) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CampaignEligibility) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CampaignEligibility) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CampaignEligibility) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CampaignEligibility) SetDescription(v string) {
	o.Description = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *CampaignEligibility) GetStartTime() time.Time {
	if o == nil || o.StartTime == nil {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *CampaignEligibility) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *CampaignEligibility) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *CampaignEligibility) GetEndTime() time.Time {
	if o == nil || o.EndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || o.EndTime == nil {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *CampaignEligibility) HasEndTime() bool {
	if o != nil && o.EndTime != nil {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *CampaignEligibility) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CampaignEligibility) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetAttributesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CampaignEligibility) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *CampaignEligibility) SetAttributes(v map[string]interface{}) {
	o.Attributes = &v
}

// GetState returns the State field value
func (o *CampaignEligibility) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CampaignEligibility) SetState(v string) {
	o.State = v
}

// GetTags returns the Tags field value
func (o *CampaignEligibility) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetTagsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *CampaignEligibility) SetTags(v []string) {
	o.Tags = v
}

// GetFeatures returns the Features field value
func (o *CampaignEligibility) GetFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetFeaturesOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *CampaignEligibility) SetFeatures(v []string) {
	o.Features = v
}

// GetEligibility returns the Eligibility field value
func (o *CampaignEligibility) GetEligibility() []CampaignEligibilityDetails {
	if o == nil {
		var ret []CampaignEligibilityDetails
		return ret
	}

	return o.Eligibility
}

// GetEligibilityOk returns a tuple with the Eligibility field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetEligibilityOk() (*[]CampaignEligibilityDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Eligibility, true
}

// SetEligibility sets field value
func (o *CampaignEligibility) SetEligibility(v []CampaignEligibilityDetails) {
	o.Eligibility = v
}

// GetRules returns the Rules field value
func (o *CampaignEligibility) GetRules() []RuleMetadataEligibility {
	if o == nil {
		var ret []RuleMetadataEligibility
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetRulesOk() (*[]RuleMetadataEligibility, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rules, true
}

// SetRules sets field value
func (o *CampaignEligibility) SetRules(v []RuleMetadataEligibility) {
	o.Rules = v
}

// GetExperiment returns the Experiment field value if set, zero value otherwise.
func (o *CampaignEligibility) GetExperiment() CampaignEligibilityExperiment {
	if o == nil || o.Experiment == nil {
		var ret CampaignEligibilityExperiment
		return ret
	}
	return *o.Experiment
}

// GetExperimentOk returns a tuple with the Experiment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibility) GetExperimentOk() (*CampaignEligibilityExperiment, bool) {
	if o == nil || o.Experiment == nil {
		return nil, false
	}
	return o.Experiment, true
}

// HasExperiment returns a boolean if a field has been set.
func (o *CampaignEligibility) HasExperiment() bool {
	if o != nil && o.Experiment != nil {
		return true
	}

	return false
}

// SetExperiment gets a reference to the given CampaignEligibilityExperiment and assigns it to the Experiment field.
func (o *CampaignEligibility) SetExperiment(v CampaignEligibilityExperiment) {
	o.Experiment = &v
}

func (o CampaignEligibility) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.EndTime != nil {
		toSerialize["endTime"] = o.EndTime
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if true {
		toSerialize["state"] = o.State
	}
	if true {
		toSerialize["tags"] = o.Tags
	}
	if true {
		toSerialize["features"] = o.Features
	}
	if true {
		toSerialize["eligibility"] = o.Eligibility
	}
	if true {
		toSerialize["rules"] = o.Rules
	}
	if o.Experiment != nil {
		toSerialize["experiment"] = o.Experiment
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignEligibility struct {
	value *CampaignEligibility
	isSet bool
}

func (v NullableCampaignEligibility) Get() *CampaignEligibility {
	return v.value
}

func (v *NullableCampaignEligibility) Set(val *CampaignEligibility) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignEligibility) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignEligibility) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCampaignEligibility(val *CampaignEligibility) *NullableCampaignEligibility {
	return &NullableCampaignEligibility{value: val, isSet: true}
}

func (v NullableCampaignEligibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignEligibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
