/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package talon

import (
	"encoding/json"
)

// ActivateLoyaltyPointsResponse struct for ActivateLoyaltyPointsResponse
type ActivateLoyaltyPointsResponse struct {
	// Updated ledger entries after activation.
	LedgerEntries *[]LoyaltyLedgerEntry `json:"ledgerEntries,omitempty"`
}

// NewActivateLoyaltyPointsResponse instantiates a new ActivateLoyaltyPointsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildActivateLoyaltyPointsResponse() *ActivateLoyaltyPointsResponse {
	this := ActivateLoyaltyPointsResponse{}
	return &this
}

// NewActivateLoyaltyPointsResponseWithDefaults instantiates a new ActivateLoyaltyPointsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateLoyaltyPointsResponseWithDefaults() *ActivateLoyaltyPointsResponse {
	this := ActivateLoyaltyPointsResponse{}
	return &this
}

// GetLedgerEntries returns the LedgerEntries field value if set, zero value otherwise.
func (o *ActivateLoyaltyPointsResponse) GetLedgerEntries() []LoyaltyLedgerEntry {
	if o == nil || o.LedgerEntries == nil {
		var ret []LoyaltyLedgerEntry
		return ret
	}
	return *o.LedgerEntries
}

// GetLedgerEntriesOk returns a tuple with the LedgerEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActivateLoyaltyPointsResponse) GetLedgerEntriesOk() (*[]LoyaltyLedgerEntry, bool) {
	if o == nil || o.LedgerEntries == nil {
		return nil, false
	}
	return o.LedgerEntries, true
}

// HasLedgerEntries returns a boolean if a field has been set.
func (o *ActivateLoyaltyPointsResponse) HasLedgerEntries() bool {
	if o != nil && o.LedgerEntries != nil {
		return true
	}

	return false
}

// SetLedgerEntries gets a reference to the given []LoyaltyLedgerEntry and assigns it to the LedgerEntries field.
func (o *ActivateLoyaltyPointsResponse) SetLedgerEntries(v []LoyaltyLedgerEntry) {
	o.LedgerEntries = &v
}

func (o ActivateLoyaltyPointsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LedgerEntries != nil {
		toSerialize["ledgerEntries"] = o.LedgerEntries
	}
	return json.Marshal(toSerialize)
}

type NullableActivateLoyaltyPointsResponse struct {
	value *ActivateLoyaltyPointsResponse
	isSet bool
}

func (v NullableActivateLoyaltyPointsResponse) Get() *ActivateLoyaltyPointsResponse {
	return v.value
}

func (v *NullableActivateLoyaltyPointsResponse) Set(val *ActivateLoyaltyPointsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateLoyaltyPointsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateLoyaltyPointsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableActivateLoyaltyPointsResponse(val *ActivateLoyaltyPointsResponse) *NullableActivateLoyaltyPointsResponse {
	return &NullableActivateLoyaltyPointsResponse{value: val, isSet: true}
}

func (v NullableActivateLoyaltyPointsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateLoyaltyPointsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
