/*
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package talon

import (
	"time"
)

// 
type Referral struct {

	// Unique ID for this entity.
	Id int32 `json:"id"`

	// The exact moment this entity was created.
	Created time.Time `json:"created"`

	// ID of the campaign from which the referral received the referral code.
	CampaignId int32 `json:"campaignId"`

	// The Integration Id of the Advocate's Profile
	AdvocateProfileIntegrationId string `json:"advocateProfileIntegrationId"`

	// An optional Integration ID of the Friend's Profile
	FriendProfileIntegrationId string `json:"friendProfileIntegrationId,omitempty"`

	// Timestamp at which point the referral code becomes valid.
	StartDate time.Time `json:"startDate,omitempty"`

	// Expiry date of the referral code. Referral never expires if this is omitted, zero, or negative.
	ExpiryDate time.Time `json:"expiryDate,omitempty"`

	// The actual referral code.
	Code string `json:"code"`

	// The number of times this referral code has been successfully used.
	UsageCounter int32 `json:"usageCounter"`

	// The number of times a referral code can be used. This can be set to 0 for no limit, but any campaign usage limits will still apply. 
	UsageLimit int32 `json:"usageLimit"`
}
