name: Publish package after release was published

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # get full history so we can diff
      - name: Publish new version
        if: ${{ steps.get_version.outputs.version != '' }}
        run: |
            make update-pkg-cache
